// Crea una base desechable. No ejecuta escrituras en hospital_rip.
import mysql from 'mysql2/promise';
import {readFile} from 'node:fs/promises';
import {spawn} from 'node:child_process';
import assert from 'node:assert/strict';
import {seed} from '../scripts/seed.js';
import {schemaForDatabase} from '../scripts/setup-schema.js';
const credentials=JSON.parse(await readFile(new URL('../data/local-admin.json',import.meta.url),'utf8'));
const db=await mysql.createConnection({...credentials,multipleStatements:true});
const name=`hospital_rip_test_${Date.now()}`,port=3091,origin=`http://localhost:${port}`;let child,checks=0;
const check=(condition,label)=>{assert.ok(condition,label);checks++;console.log(`OK ${checks}: ${label}`);};
const call=async(path,body,cookie='')=>{const res=await fetch(origin+'/api/'+path,{method:body?'POST':'GET',headers:{Origin:origin,...(body?{'Content-Type':'application/json'}:{}),Cookie:cookie},body:body?JSON.stringify(body):undefined});return {status:res.status,body:await res.json(),cookie:res.headers.get('set-cookie')?.split(';')[0]};};
try{
 await db.query(schemaForDatabase(await readFile(new URL('../database/schema.sql',import.meta.url),'utf8'),name));await seed(db);
 child=spawn(process.execPath,['server/index.js'],{env:{...process.env,DB_NAME:name,DB_USER:credentials.user,DB_PASSWORD:credentials.password,DB_PORT:String(credentials.port),PORT:String(port),APP_ORIGIN:origin},stdio:'ignore',windowsHide:true});
 for(let i=0;i<40;i++){try{await fetch(origin);break;}catch{await new Promise(r=>setTimeout(r,250));}}
 check((await call('data')).status===401,'API protegida sin sesión');
 check((await call('login',{email:'admin@hospital.local',password:'Incorrecta!'})).status===401,'Contraseña incorrecta rechazada');
 const admin=await call('login',{email:'admin@hospital.local',password:'Hospital2026!'}),chief=await call('login',{email:'jefe@hospital.local',password:'Hospital2026!'}),supervisor=await call('login',{email:'supervisor@hospital.local',password:'Hospital2026!'});
 check([admin,chief,supervisor].every(r=>r.status===200),'Acceso con los tres roles');
 const a=admin.cookie,c=chief.cookie,s=supervisor.cookie;
 check((await call('users',{name:'Intruso',email:'intruso@hospital.local',role:'admin',password:'Hospital2026!'},c)).status===403,'Médico jefe no crea usuarios');
 check((await call('departments',{name:'Intruso'},a)).status===403,'Administrador no suplanta funciones del supervisor');
 check((await call('reports?start=2026-01-01&end=2026-12-31',null,c)).status===403,'Reportes exclusivos de administrador');
 let snapshot=(await call('data',null,c)).body;check(!snapshot.users&&!snapshot.audit,'Datos administrativos ocultos para médico jefe');
 const planId=(await call('plans',{name:'Prueba integral',start_date:'2030-01-01',end_date:'2030-01-07'},c)).body.id;check(Boolean(planId),'Crea planificación');
 check((await call('plans/submit',{id:planId},c)).status===400,'No envía planificación vacía');
 const disposablePlan=(await call('plans',{name:'Borrador descartable',start_date:'2030-02-01',end_date:'2030-02-02'},c)).body.id;
 check((await call('plans/delete',{id:disposablePlan},c)).status===200,'Elimina planificación en borrador');
 check(!(await call('data',null,c)).body.plans.some(p=>p.id===disposablePlan),'Planificación eliminada no permanece en el listado');
 const deptId=(await call('departments',{name:'Área de pruebas',description:'Temporal',color:'#537fa6'},s)).body.id;check(Boolean(deptId),'Registra departamento');
 const doctorId=(await call('doctors',{name:'Médico de prueba',identification:'TEST-2030',specialty:'General',department_id:deptId},s)).body.id;check(Boolean(doctorId),'Registra médico');
 check((await call('doctors',{name:'Duplicado',identification:'TEST-2030',specialty:'General',department_id:deptId},s)).status===409,'Bloquea identificación duplicada');
 const shift={plan_id:planId,department_id:deptId,doctor_id:doctorId,starts_at:'2030-01-01T07:00',ends_at:'2030-01-01T15:00',label:'Guardia de prueba'};
 check((await call('shifts',shift,c)).status===400,'Bloquea asignación sin disponibilidad');
 const availabilityId=(await call('availability',{doctor_id:doctorId,starts_at:'2030-01-01T00:00',ends_at:'2030-01-08T00:00'},s)).body.id;check(Boolean(availabilityId),'Registra intervalo disponible');
 check((await call('availability',{id:availabilityId,doctor_id:doctorId,starts_at:'2030-01-01T00:00',ends_at:'2030-01-09T00:00'},s)).status===200,'Edita disponibilidad sin guardias asignadas');
 check((await call('departments',{id:deptId,name:'Área de pruebas',description:'Temporal',color:'#537fa6',active:false},s)).status===400,'Protege departamento con médicos activos');
 check((await call('shifts',{...shift,department_id:1},c)).status===400,'Bloquea departamento incorrecto');
 const shiftId=(await call('shifts',shift,c)).body.id;check(Boolean(shiftId),'Asigna guardia compatible');
 check((await call('shifts',shift,c)).status===409,'Bloquea guardias superpuestas');
 check((await call('shifts',{...shift,starts_at:'2030-01-10T07:00',ends_at:'2030-01-10T15:00'},c)).status===400,'Bloquea guardia fuera del período');
 check((await call('availability',{id:availabilityId,doctor_id:doctorId,starts_at:'2030-01-01T00:00',ends_at:'2030-01-10T00:00'},s)).status===400,'Protege disponibilidad con guardias al editar');
 check((await call('availability/delete',{id:availabilityId},s)).status===400,'Protege disponibilidad con asignación');
 check((await call('doctors',{id:doctorId,name:'Médico de prueba',identification:'TEST-2030',specialty:'General',department_id:deptId,active:false},s)).status===400,'Protege médico con guardias futuras');
 const task={plan_id:planId,department_id:deptId,title:'Cobertura prioritaria de prueba',priority:'high'},taskId=(await call('tasks',task,c)).body.id;check(Boolean(taskId),'Crea tarea prioritaria');
 check((await call('plans/submit',{id:planId},c)).status===400,'Bloquea envío con tarea prioritaria sin cubrir');
 check((await call('tasks',{...task,id:taskId,shift_id:shiftId},c)).status===200,'Vincula tarea con guardia');
 check((await call('plans/submit',{id:planId},c)).status===200,'Envía propuesta completa a revisión');
 check((await call('shifts',{...shift,id:shiftId},c)).status===409,'Bloquea edición en revisión');
 let p=(await call('data',null,s)).body.plans.find(p=>p.id===planId);
 check((await call('plans/review',{id:planId,version:p.version,status:'approved'},c)).status===403,'Médico jefe no puede autorizar');
 check((await call('plans/review',{id:planId,version:p.version-1,status:'approved'},s)).status===409,'Revisión exige versión actual');
 check((await call('plans/review',{id:planId,version:p.version,status:'rejected',note:''},s)).status===400,'Rechazo requiere observación');
 check((await call('plans/review',{id:planId,version:p.version,status:'rejected',note:'Revisar cobertura antes de aprobar.'},s)).status===200,'Supervisor rechaza con observación');
 check((await call('shifts',{...shift,id:shiftId,label:'Guardia corregida'},c)).status===200,'Planificación rechazada vuelve a edición');
 check((await call('plans/submit',{id:planId},c)).status===200,'Reenvío a revisión');
 p=(await call('data',null,s)).body.plans.find(p=>p.id===planId);
 check((await call('plans/review',{id:planId,version:p.version,status:'approved',note:'Cobertura revisada.'},s)).status===200,'Supervisor autoriza planificación');
 check((await call('shifts/delete',{id:shiftId},c)).status===409,'Guardias autorizadas quedan inmutables');
 const reports=(await call('reports?start=2030-01-01&end=2030-01-07',null,a)).body;check(reports.items.length===1&&reports.items[0].status==='approved','Reporte refleja período y autorización');
 check((await call('reports?start=2030-02-01&end=2030-01-01',null,a)).status===400,'Rechaza período invertido');
 check((await call('users',{id:1,name:'Samuel Flórez',email:'admin@hospital.local',role:'chief',active:true},a)).status===400,'Conserva último administrador');
 const newUser=(await call('users',{name:'Usuario prueba',email:'prueba@hospital.local',role:'chief',password:'Contraseña2030!'},a)).body.id;check(Boolean(newUser),'Administrador crea cuenta');
 const other=(await call('login',{email:'prueba@hospital.local',password:'Contraseña2030!'})).cookie;
 await call('users',{id:newUser,name:'Usuario prueba',email:'prueba@hospital.local',role:'chief',active:false},a);
 check((await call('data',null,other)).status===401,'Desactivar cuenta revoca sesión');
 check((await call('data',null,a)).body.audit.some(e=>e.action==='plans/review'),'Auditoría registra revisión');
 const noOrigin=await fetch(origin+'/api/plans',{method:'POST',headers:{Cookie:c,'Content-Type':'application/json'},body:'{}'});check(noOrigin.status===403,'Rechaza mutación sin origen permitido');
 const worker={name:'Trabajador de prueba',identification:'PAY-001',position:'Auxiliar',hourly_rate:'25000'};
 check((await call('workers',worker,s)).status===403,'Supervisor no administra nómina');
 check(!(await call('data',null,c)).body.workers,'Nómina oculta para médico jefe');
 const workerId=(await call('workers',worker,a)).body.id;check(Boolean(workerId),'Registra trabajador por horas');
 check((await call('workers',{...worker,hourly_rate:-1},a)).status===400,'Rechaza tarifa negativa');
 const hours={worker_id:workerId,starts_at:'2020-01-01T22:00',ends_at:'2020-01-02T06:00'};
 const hoursId=(await call('work-hours',hours,a)).body.id;check(Boolean(hoursId),'Registra ocho horas cruzando medianoche');
 check((await call('work-hours',hours,a)).status===409,'Rechaza jornadas superpuestas');
 check((await call('work-hours',{...hours,starts_at:'2099-01-01T07:00',ends_at:'2099-01-01T08:00'},a)).status===400,'Rechaza jornadas futuras');
 await call('workers',{...worker,id:workerId,hourly_rate:'30000'},a);
 const period={worker_id:workerId,start_date:'2020-01-01',end_date:'2020-01-02'};
 const payrollId=(await call('payrolls',period,a)).body.id;check(Boolean(payrollId),'Liquida horas pendientes');
 const pay=(await call('data',null,a)).body.payrolls.find(p=>p.id===payrollId);
 check(Number(pay.total_cents)===20000000&&pay.minutes===480,'Conserva tarifa histórica y calcula salario de 200000 COP');
 check((await call('payrolls',period,a)).status===400,'No liquida dos veces las mismas horas');
 check((await call('work-hours/delete',{id:hoursId},a)).status===409,'Protege jornadas liquidadas');
 check((await call('payrolls/pay',{id:payrollId,reference:'Transferencia prueba'},a)).status===200,'Registra pago con comprobante');
 check((await call('payrolls/pay',{id:payrollId,reference:'Duplicado'},a)).status===409,'Rechaza pago duplicado');
 await call('logout',{},c);check((await call('data',null,c)).status===401,'Cerrar sesión revoca acceso');
 console.log(`\n${checks} comprobaciones de integración correctas. Base temporal eliminada al finalizar.`);
}finally{if(child){child.kill();await new Promise(r=>setTimeout(r,400));}if(!/^hospital_rip_test_\d+$/.test(name))throw Error('Nombre temporal inesperado');await db.query(`DROP DATABASE IF EXISTS \`${name}\``);await db.end();}
