const $=(q,root=document)=>root.querySelector(q);
function money(cents){return (Number(cents)/100).toLocaleString('es-CO',{style:'currency',currency:'COP',minimumFractionDigits:2});}
function payrollPage(){
 const workers=data.workers||[],hours=data.workHours||[],payments=data.payrolls||[];
 return heading('Nómina y pagos','Salario del período = horas trabajadas × tarifa por hora. Valores en pesos colombianos.',btn('Registrar trabajador','new-worker','plus','primary')+btn('Registrar jornada','new-work-hours','clock')+btn('Liquidar horas','new-payroll','check'))+
 `<p class="form-help">Registra jornadas ya trabajadas. Cada jornada conserva su tarifa y solo puede liquidarse una vez. Marcar como pagado registra un pago realizado por fuera del sistema.</p>`+
 `<section class="panel"><div class="panel-head"><h2>Trabajadores</h2></div>`+table(['Trabajador','Identificación','Cargo','Tarifa por hora','Estado',''],workers.map(w=>`<tr><td>${esc(w.name)}</td><td>${esc(w.identification)}</td><td>${esc(w.position)}</td><td>${money(w.rate_cents)}</td><td>${w.active?'Activo':'Inactivo'}</td><td>${btn('Editar','edit-worker','edit','small',`data-id="${w.id}"`)}</td></tr>`).join(''))+`</section>`+
 `<section class="panel"><div class="panel-head"><h2>Jornadas trabajadas</h2></div>`+table(['Trabajador','Inicio','Fin','Horas','Tarifa','Observación','Estado',''],hours.map(h=>`<tr><td>${esc(h.worker_name)}</td><td>${esc(h.starts_at)}</td><td>${esc(h.ends_at)}</td><td>${(h.minutes/60).toFixed(2)}</td><td>${money(h.rate_cents)}</td><td>${esc(h.note)}</td><td>${h.payroll_id?'Liquidación #'+h.payroll_id:'Pendiente'}</td><td>${h.payroll_id?'':btn('Retirar','delete-work-hours','','small',`data-id="${h.id}"`)}</td></tr>`).join(''))+`</section>`+
 `<section class="panel"><div class="panel-head"><h2>Liquidaciones e historial de pagos</h2><div class="actions">${btn('Exportar CSV','export-payroll','download')}${btn('Imprimir','print')}</div></div>`+table(['Número','Trabajador','Período','Horas','Salario','Estado','Referencia',''],payments.map(p=>`<tr><td>#${p.id}</td><td>${esc(p.worker_name)}</td><td>${esc(p.start_date)} / ${esc(p.end_date)}</td><td>${(p.minutes/60).toFixed(2)}</td><td>${money(p.total_cents)}</td><td>${p.status==='paid'?'Pagado':'Pendiente'}</td><td>${esc(p.reference)}</td><td>${p.status==='paid'?'':btn('Registrar pago','pay-payroll','check','small',`data-id="${p.id}"`)}</td></tr>`).join(''))+`</section>`;
}
function workerForm(w={}){modal(w.id?'Editar trabajador':'Registrar trabajador',input('Nombre completo','name',w.name,'text','required maxlength="100"')+input('Identificación','identification',w.identification,'text','required maxlength="30"')+input('Cargo','position',w.position,'text','required maxlength="100"')+input('Tarifa por hora en COP','hourly_rate',w.rate_cents?w.rate_cents/100:'','number','required min="0.01" max="999999999.99" step="0.01"')+(w.id?`<label class="check"><input type="checkbox" name="active" ${w.active?'checked':''}>Trabajador activo</label>`:'')+`<p class="form-help">Los cambios de tarifa se aplican a las nuevas jornadas. Las anteriores conservan la tarifa registrada.</p>`,b=>api('workers',{...b,id:w.id}));}
function workerOptions(){return data.workers.filter(w=>w.active).map(w=>[w.id,w.name]);}
function workHoursForm(){if(!workerOptions().length)return toast('Registra un trabajador activo primero.');modal('Registrar jornada trabajada',select('Trabajador','worker_id',workerOptions())+input('Inicio en hora de Colombia','starts_at',today()+'T07:00','datetime-local','required')+input('Fin en hora de Colombia','ends_at',today()+'T15:00','datetime-local','required')+input('Observación opcional','note','','text','maxlength="400"')+`<p class="form-help">La duración y el salario se calculan en el servidor. Máximo 24 horas por jornada, sin cruces.</p>`,b=>api('work-hours',b));}
function payrollForm(){const options=data.workers.filter(w=>data.workHours.some(h=>h.worker_id===w.id&&!h.payroll_id)).map(w=>[w.id,w.name]);if(!options.length)return toast('No hay jornadas pendientes de liquidación.');modal('Liquidar horas trabajadas',select('Trabajador','worker_id',options)+input('Desde','start_date',today().slice(0,8)+'01','date','required')+input('Hasta inclusive','end_date',today(),'date','required')+`<p class="form-help">Se incluyen únicamente jornadas completas dentro del período que todavía no se hayan liquidado. Cada jornada se redondea al centavo. La liquidación queda pendiente de pago.</p>`,b=>api('payrolls',b));}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={home:'M3 10 12 3l9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1Z',calendar:'M4 5h16v16H4z M7 3v4m10-4v4M4 10h16m-12 4h1m3 0h1m3 0h1m-9 4h1m3 0h1',users:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2m20 0v-2a4 4 0 0 0-3-3.87M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8m7-8a4 4 0 0 1 0 8',building:'M4 21V7h6V3h10v18M2 21h20M7 11h0m0 4h0m7-8h2m-2 4h2m-2 4h2m-5 6v-4h4v4',clock:'M12 8v5l3 2M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',check:'m5 12 4 4L19 6',shield:'m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6zm-4 9 3 3 5-6',chart:'M4 3v18h17M8 16v-4m5 4V8m5 8V5',list:'M9 5h12M9 12h12M9 19h12M3 5h1m-1 7h1m-1 7h1',plus:'M12 5v14M5 12h14',arrow:'M5 12h14m-5-5 5 5-5 5',left:'m14 6-6 6 6 6',right:'m10 6 6 6-6 6',logout:'M9 4H4v16h5m5-13 5 5-5 5m-6-5h13',sun:'M12 3v1m0 16v1M3 12h1m16 0h1M5.6 5.6l.7.7m11.4 11.4.7.7m0-12.8-.7.7M6.3 17.7l-.7.7M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0',menu:'M4 6h16M4 12h16M4 18h16',close:'m6 6 12 12M6 18 18 6',edit:'m15 4 5 5M4 20l5-1L21 7l-5-5L4 14Z',download:'M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4',lock:'M5 11h14v10H5zm3 0V7a4 4 0 0 1 8 0v4m-4 4v2',eye:'M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12m13 0a3 3 0 1 1-6 0 3 3 0 0 1 6 0',alert:'m12 3 10 18H2zm0 6v5m0 3v1',refresh:'M20 7v5h-5M4 17v-5h5M5 8a8 8 0 0 1 13-3l2 3M4 16l2 3a8 8 0 0 0 13-3'};
const icon=name=>`<svg class="icon" aria-hidden="true" viewBox="0 0 24 24"><path d="${paths[name]||paths.list}"/></svg>`;
const roleNames={admin:'Administrador',supervisor:'Supervisor',chief:'Médico jefe'};
const states={draft:'Borrador',pending:'En revisión',approved:'Autorizada',rejected:'Rechazada',high:'Alta prioridad',normal:'Normal'};
const tag=value=>`<span class="tag ${esc(value)}">${esc(states[value]||value)}</span>`;
const initials=name=>name.split(' ').slice(0,2).map(x=>x[0]).join('');
const fmt=(value,options={day:'numeric',month:'short'})=>new Date(value.slice(0,10)+'T12:00:00').toLocaleDateString('es-CO',options);
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const addDays=(value,n)=>{const d=new Date(value+'T12:00:00');d.setDate(d.getDate()+n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
let user=null,data={},view='home',selectedPlan=null,week=today(),search='',departmentFilter='',report=null;
try{document.body.dataset.theme=localStorage.getItem('rip-theme')||'light';}catch{}
const dep=id=>data.departments.find(d=>d.id===+id);
const doc=id=>data.doctors.find(d=>d.id===+id);
const btn=(label,action,ico='',klass='',attrs='')=>`<button type="button" class="btn ${klass}" data-action="${action}" ${attrs}>${ico?icon(ico):''}${label}</button>`;
const input=(label,name,value='',type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const select=(label,name,items,value='',optional=false)=>`<label>${label}<select name="${name}" ${optional?'':'required'}>${optional?'<option value="">Sin asignar</option>':''}${items.map(([id,label])=>`<option value="${esc(id)}" ${String(id)===String(value)?'selected':''}>${esc(label)}</option>`).join('')}</select></label>`;
const departmentOptions=()=>data.departments.filter(d=>d.active).map(d=>[d.id,d.name]);
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4500);}
async function api(path,body){const res=await fetch('/api/'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const result=await res.json();if(!res.ok){if(res.status===401&&path!=='login'){user=null;$('#modal').close();login();}throw Error(result.error);}return result;}
async function refresh(){data=await api('data');render();}
function login(){ $('#app').innerHTML=`<section class="login"><div class="login-story"><a class="brand" href="/"><img src="/mark.svg" alt="">Hospital RIP<small></small></a><div><div class="eyebrow">Sistema de gestión hospitalaria</div><h1>Cuidar comienza<br>con una buena<br><span>organización.</span></h1><p class="intro">Un espacio para coordinar a nuestro equipo médico y dar a cada guardia la atención que merece.</p><div class="login-steps"><span><b>01</b>Planificar</span><span><b>02</b>Revisar</span><span><b>03</b>Autorizar</span></div></div><small>HOSPITAL RIP &nbsp; / &nbsp; GESTIÓN DEL PERSONAL MÉDICO</small></div><div class="login-side"><div class="login-card"><div class="department-icon">${icon('lock')}</div><div class="eyebrow">Bienvenido a tu espacio</div><h2>Iniciar sesión</h2><p>Ingresa con tu cuenta institucional para continuar.</p><form id="login-form">${input('Correo electrónico','email','','email','required autocomplete="username" placeholder="nombre@hospital.local"')}<label>Contraseña<div class="password-wrap"><input name="password" type="password" required autocomplete="current-password" placeholder="Ingresa tu contraseña"><button type="button" data-action="toggle-password" aria-label="Mostrar contraseña">${icon('eye')}</button></div></label><p class="form-error" role="alert"></p><button class="btn primary" type="submit">Ingresar al sistema ${icon('arrow')}</button></form><footer>Acceso exclusivo para personal autorizado.<br>Si necesitas una cuenta, contacta al administrador.</footer></div></div></section>`;$('#login-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,submit=$('[type=submit]',f);submit.disabled=true;try{user=(await api('login',Object.fromEntries(new FormData(f)))).user;view='home';history.replaceState(null,'','#home');selectedPlan=null;report=null;await refresh();}catch(err){$('.form-error',f).textContent=err.message;}finally{submit.disabled=false;}};}
const navItems=()=>[['home','Resumen general','home'],['plans','Planificación','calendar'],['doctors','Personal médico','users'],['departments','Departamentos','building'],['availability','Disponibilidad','clock'],['tasks','Tareas prioritarias','list'],...(user.role==='supervisor'?[['reviews','Autorizaciones','shield']]:[]),...(user.role==='admin'?[['payroll','Nómina y pagos','clock'],['users','Usuarios y roles','shield'],['reports','Reportes','chart'],['audit','Actividad','list']]:[])];
function render(){if(!user)return login();const items=navItems();if(!items.some(x=>x[0]===view))view='home';const title=items.find(x=>x[0]===view)?.[1];$('#app').innerHTML=`<aside class="sidebar"><a class="brand" href="#home"><img src="/mark.svg" alt=""><span>Hospital RIP<small>COORDINACIÓN MÉDICA</small></span></a><div class="nav-label">ESPACIO DE TRABAJO</div><nav>${items.map(([key,label,ico])=>`<a class="nav-item ${view===key?'active':''}" href="#${key}">${icon(ico)}${label}${key==='reviews'&&data.plans.filter(p=>p.status==='pending').length?`<span class="count">${data.plans.filter(p=>p.status==='pending').length}</span>`:''}</a>`).join('')}</nav><div class="sidebar-bottom"><div class="hospital-note">${icon('shield')} <strong>Una atención bien coordinada</strong><p>Cada guardia autorizada comienza con un equipo organizado.</p></div><div class="user"><span class="avatar">${initials(user.name)}</span><span><strong>${esc(user.name)}</strong><small>${roleNames[user.role]}</small></span></div>${btn('Cerrar sesión','logout','logout','plain logout')}</div></aside><div class="workspace"><header class="topbar"><div class="breadcrumb"><button class="icon-btn mobile-menu" data-action="menu" aria-label="Abrir menú">${icon('menu')}</button><span>Hospital RIP</span><span>/</span><strong>${title}</strong></div><div class="top-actions"><span class="top-date">${fmt(today(),{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</span><span class="divider"></span><button class="icon-btn" data-action="theme" aria-label="Cambiar tema">${icon('sun')}</button>${btn('Mi cuenta','account','users','plain')}<span class="avatar">${initials(user.name)}</span></div></header><main id="content">${content()}</main><footer class="footer"><span>Hospital RIP · Sistema de gestión hospitalaria</span><span>Hora local de Colombia · Versión 1.4</span></footer></div>`;bindPage();}
function heading(title,subtitle,actions='',eyebrow='Coordinación hospitalaria'){return `<div class="page-title"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${subtitle}</p></div><div class="actions">${actions}</div></div>`;}
function empty(title,description,action=''){return `<div class="empty">${icon('calendar')}<strong>${title}</strong><p>${description}</p>${action}</div>`;}
function table(headers,rowsHtml){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rowsHtml}</tbody></table></div>`;}
function stat(label,value,foot,ico){return `<div class="stat"><div class="stat-label">${label}${icon(ico)}</div><div class="stat-value">${value}</div><div class="stat-foot">${foot}</div></div>`;}
function stats(){const open=data.shifts.filter(s=>!s.doctor_id).length;return `<div class="stats">${stat('Personal médico',data.doctors.filter(d=>d.active).length,'<span class="dot"></span>Médicos activos','users')}${stat('Guardias programadas',data.shifts.length,'En todas las planificaciones','calendar')}${stat('Por cubrir',open,`<span class="dot ${open?'orange':''}"></span>${open?'Pendientes de asignación':'Cobertura completa'}`,'clock')}${stat('En revisión',data.plans.filter(p=>p.status==='pending').length,'Pendientes de autorización','shield')}</div>`;}
function content(){if(view==='payroll')return payrollPage();if(view==='home')return dashboard();if(view==='plans'||view==='reviews')return selectedPlan?planDetail():plansPage();if(view==='doctors')return doctorsPage();if(view==='departments')return departmentsPage();if(view==='availability')return availabilityPage();if(view==='tasks')return tasksPage();if(view==='users')return usersPage();if(view==='reports')return reportsPage();if(view==='audit')return auditPage();}
function dashboard(){const covered=data.shifts.filter(s=>s.doctor_id).length,total=data.shifts.length,coverage=total?Math.round(covered/total*100):0;return heading(`Todo listo para coordinar, ${esc(user.name.split(' ')[0])}.`,'Una mirada al equipo, las guardias y las prioridades del hospital.',user.role==='chief'?btn('Nueva planificación','new-plan','plus','primary'):btn('Ver planificaciones','go-plans','calendar','primary'),'Tu hospital, en orden')+stats()+`<div class="dashboard-grid"><div><section class="panel"><div class="panel-head"><div><h2>Agenda de guardias</h2><p>${fmt(week)} — ${fmt(addDays(week,6),{day:'numeric',month:'long',year:'numeric'})}</p></div><div class="calendar-tools">${btn('Hoy','today','','small')}<button class="icon-btn" data-action="previous-week" aria-label="Semana anterior">${icon('left')}</button><button class="icon-btn" data-action="next-week" aria-label="Semana siguiente">${icon('right')}</button></div></div>${calendar()}<div class="calendar-legend">${data.departments.map(d=>`<span style="--event:${esc(d.color)}"><i></i>${esc(d.name)}</span>`).join('')}</div></section><section class="panel"><div class="panel-head"><div><h2>Planificaciones recientes</h2><p>Seguimiento de las propuestas del equipo médico</p></div><a class="btn plain small" href="#plans">Ver todas ${icon('arrow')}</a></div>${planTable(data.plans.slice(0,4))}</section></div><aside class="dashboard-aside"><section class="panel priority-panel"><span class="tag high">${icon('alert')} Atención prioritaria</span><h2>Primero, lo importante</h2><p class="muted">Tareas que requieren cobertura en la planificación.</p>${data.tasks.filter(t=>t.priority==='high').slice(0,4).map(t=>`<div class="task-card"><small class="muted">${esc(dep(t.department_id)?.name)}</small><h3>${esc(t.title)}</h3><p>${t.shift_id?'Guardia vinculada':'Pendiente de vincular'}</p></div>`).join('')||'<p class="muted">No hay tareas de alta prioridad.</p>'}<a class="btn small" href="#tasks">Consultar tareas ${icon('arrow')}</a></section><section class="panel coverage"><h3>Cobertura de guardias</h3><strong>${coverage}<small>%</small></strong><div class="progress"><span style="width:${coverage}%"></span></div><p>${covered} de ${total} guardias tienen médico asignado.</p><small class="muted">Incluye borradores y planes en revisión.</small></section></aside></div>`;}
function calendar(){const days=Array.from({length:7},(_,i)=>addDays(week,i));return `<div class="calendar-wrap"><div class="calendar">${days.map(d=>`<div class="cal-head ${d===today()?'today':''}"><small>${fmt(d,{weekday:'short'})}</small><strong>${+d.slice(8)}</strong></div>`).join('')}${days.map(day=>`<div class="cal-day">${data.shifts.filter(s=>s.starts_at.slice(0,10)===day).map(s=>`<button class="cal-event" style="--event:${esc(dep(s.department_id)?.color)}" data-action="open-plan" data-id="${s.plan_id}" title="${esc(dep(s.department_id)?.name+' · '+(doc(s.doctor_id)?.name||'Sin asignar'))}"><span class="time">${s.starts_at.slice(11,16)} – ${s.ends_at.slice(11,16)}</span><strong>${esc(dep(s.department_id)?.name)}</strong><small>${esc(doc(s.doctor_id)?.name.split(' ').slice(0,2).join(' ')||'Por asignar')}</small></button>`).join('')||'<small class="muted">Sin guardias</small>'}</div>`).join('')}</div></div>`;}
function planTable(items){return items.length?table(['Planificación','Período','Cobertura','Estado',''],items.map(p=>{const shifts=data.shifts.filter(s=>s.plan_id===p.id);return `<tr><td><strong>${esc(p.name)}</strong><small>${esc(p.author_name)}</small></td><td>${fmt(p.start_date)} — ${fmt(p.end_date)}</td><td>${shifts.filter(s=>s.doctor_id).length} / ${shifts.length} guardias</td><td>${tag(p.status)}</td><td>${btn('Ver detalle','open-plan','right','small',`data-id="${p.id}"`)}</td></tr>`;}).join('')):empty('Sin planificaciones','Las propuestas aparecerán aquí cuando el médico jefe las registre.');}
function plansPage(){const review=view==='reviews',items=data.plans.filter(p=>(!review||p.status==='pending')&&p.name.toLowerCase().includes(search.toLowerCase()));return heading(review?'Autorizaciones':'Planificación de guardias',review?'Revisa la cobertura antes de autorizar cada propuesta.':'Organiza los turnos y envía tu propuesta al supervisor.',user.role==='chief'?btn('Nueva planificación','new-plan','plus','primary'):'')+`<div class="toolbar"><input id="search" type="search" placeholder="Buscar planificación…" aria-label="Buscar planificación" value="${esc(search)}"><span class="muted">${items.length} planificaciones</span></div><section class="panel">${planTable(items)}</section>`;}
function planDetail(){const p=data.plans.find(p=>p.id===+selectedPlan);if(!p){selectedPlan=null;return plansPage();}const shifts=data.shifts.filter(s=>s.plan_id===p.id),tasks=data.tasks.filter(t=>t.plan_id===p.id),canEdit=user.role==='chief'&&['draft','rejected'].includes(p.status);return heading(esc(p.name),`${fmt(p.start_date,{day:'numeric',month:'long'})} — ${fmt(p.end_date,{day:'numeric',month:'long',year:'numeric'})}`,btn('Volver','back-plans','left')+(canEdit?btn('Editar período','edit-plan','edit','',`data-id="${p.id}"`)+btn('Eliminar','delete-plan','','danger',`data-id="${p.id}"`)+btn('Agregar guardia','new-shift','plus','primary',`data-plan="${p.id}"`):''))+`<div class="notice ${p.status==='approved'?'approved':''}">${tag(p.status)} &nbsp; ${p.status==='approved'?'Planificación autorizada para su ejecución.':p.status==='pending'?'La propuesta está en revisión. La edición queda bloqueada hasta la decisión del supervisor.':'Completa las asignaciones y vincula las tareas de alta prioridad antes de enviar.'}${p.review_note?`<br><strong>Observación del supervisor:</strong> ${esc(p.review_note)}`:''}</div><div class="plan-detail"><div class="panel"><div class="panel-head"><div><h2>Guardias de la planificación</h2><p>${shifts.filter(s=>s.doctor_id).length} de ${shifts.length} guardias cubiertas</p></div></div>${shifts.length?table(['Guardia','Departamento','Médico',''],shifts.map(s=>`<tr><td><strong>${esc(s.label)}</strong><small>${fmt(s.starts_at)} · ${s.starts_at.slice(11,16)} a ${fmt(s.ends_at)} ${s.ends_at.slice(11,16)}</small></td><td>${esc(dep(s.department_id)?.name)}</td><td>${s.doctor_id?esc(doc(s.doctor_id)?.name):tag('Por cubrir')}</td><td>${canEdit?btn('Editar','edit-shift','edit','small',`data-id="${s.id}"`)+btn('Retirar','delete-shift','','small danger',`data-id="${s.id}"`):''}</td></tr>`).join('')):empty('Agrega la primera guardia','Selecciona un departamento, un horario y un médico disponible.')}</div><aside><section class="panel detail-aside"><h2>Tareas a considerar</h2>${tasks.map(t=>`<div class="task-card">${tag(t.priority)}<h3>${esc(t.title)}</h3><p>${esc(dep(t.department_id)?.name)} · ${t.shift_id?'Vinculada':'Sin vincular'}</p>${canEdit?btn('Editar tarea','edit-task','','small',`data-id="${t.id}"`):''}</div>`).join('')||'<p>No hay tareas registradas.</p>'}${canEdit?btn('Agregar tarea','new-task','plus','small',`data-plan="${p.id}"`):''}</section><section class="panel detail-aside"><h2>Control de la propuesta</h2><p>Creada por ${esc(p.author_name)}.<br>Versión ${p.version}${p.reviewer_name?`<br>Revisada por ${esc(p.reviewer_name)}.`:''}</p>${canEdit?btn('Enviar a revisión','submit-plan','arrow','primary',`data-id="${p.id}"`):''}${user.role==='supervisor'&&p.status==='pending'?`<div class="actions">${btn('Autorizar','approve-plan','check','primary',`data-id="${p.id}"`)}${btn('Rechazar','reject-plan','','danger',`data-id="${p.id}"`)}</div>`:''}</section></aside></div>`;}
function doctorsPage(){const items=data.doctors.filter(d=>(!departmentFilter||d.department_id===+departmentFilter)&&`${d.name} ${d.identification} ${d.specialty}`.toLowerCase().includes(search.toLowerCase()));return heading('Personal médico','El equipo que hace posible la atención de cada día.',user.role==='supervisor'?btn('Registrar médico','new-doctor','plus','primary'):'')+filters('Buscar nombre, identificación o especialidad…',items.length)+`<section class="panel">${items.length?table(['Médico','Especialidad','Departamento','Estado',''],items.map(d=>`<tr><td><div class="person-cell"><span class="avatar">${initials(d.name)}</span><span><strong>${esc(d.name)}</strong><small>${esc(d.identification)}</small></span></div></td><td>${esc(d.specialty)}</td><td>${esc(dep(d.department_id)?.name)}</td><td>${tag(d.active?'Activo':'Inactivo')}</td><td>${user.role==='supervisor'?btn('Editar','edit-doctor','edit','small',`data-id="${d.id}"`):''}</td></tr>`).join('')):empty('No hay médicos para esta búsqueda','Prueba con otro nombre o departamento.')}</section>`;}
function filters(placeholder,count){return `<div class="toolbar"><input id="search" type="search" aria-label="Buscar" placeholder="${placeholder}" value="${esc(search)}"><select id="department-filter" aria-label="Filtrar departamento"><option value="">Todos los departamentos</option>${departmentOptions().map(([id,label])=>`<option value="${id}" ${departmentFilter===String(id)?'selected':''}>${esc(label)}</option>`).join('')}</select><span class="muted">${count} registros</span></div>`;}
function departmentsPage(){return heading('Departamentos','Áreas de atención y equipos del Hospital RIP.',user.role==='supervisor'?btn('Nuevo departamento','new-department','plus','primary'):'')+`<div class="cards">${data.departments.map(d=>`<section class="department-card" style="--event:${esc(d.color)}"><div class="card-top"><div class="department-icon">${icon('building')}</div>${tag(d.active?'Activo':'Inactivo')}</div><h2>${esc(d.name)}</h2><p>${esc(d.description)||'Sin descripción registrada.'}</p><div class="card-bottom"><span>${data.doctors.filter(m=>m.department_id===d.id&&m.active).length} médicos activos</span>${user.role==='supervisor'?btn('Editar','edit-department','edit','small',`data-id="${d.id}"`)+(d.active?btn('Desactivar','deactivate-department','','small danger',`data-id="${d.id}"`):btn('Reactivar','activate-department','','small',`data-id="${d.id}"`)):''}</div></section>`).join('')}</div>`;}
function availabilityPage(){const items=data.availability.filter(a=>{const d=doc(a.doctor_id);return (!departmentFilter||d.department_id===+departmentFilter)&&d.name.toLowerCase().includes(search.toLowerCase());});return heading('Disponibilidad médica','Intervalos registrados para asignar guardias compatibles.',user.role==='supervisor'?btn('Agregar disponibilidad','new-availability','plus','primary'):'')+filters('Buscar médico…',items.length)+`<section class="panel">${items.length?table(['Médico','Departamento','Desde','Hasta',''],items.map(a=>`<tr><td><strong>${esc(doc(a.doctor_id)?.name)}</strong></td><td>${esc(dep(doc(a.doctor_id)?.department_id)?.name)}</td><td>${fmt(a.starts_at)} · ${a.starts_at.slice(11,16)}</td><td>${fmt(a.ends_at)} · ${a.ends_at.slice(11,16)}</td><td>${user.role==='supervisor'?btn('Editar','edit-availability','edit','small',`data-id="${a.id}"`)+btn('Retirar','delete-availability','','small danger',`data-id="${a.id}"`):''}</td></tr>`).join('')):empty('Sin disponibilidades','El supervisor puede agregar intervalos para el equipo médico.')}</section>`;}
function tasksPage(){const items=data.tasks.filter(t=>(!departmentFilter||t.department_id===+departmentFilter)&&t.title.toLowerCase().includes(search.toLowerCase()));return heading('Tareas prioritarias','Vincula las necesidades del hospital con una guardia de cobertura.',user.role==='chief'?btn('Nueva tarea','new-task','plus','primary'):'')+filters('Buscar tarea…',items.length)+`<section class="panel">${items.length?table(['Tarea','Departamento','Prioridad','Cobertura',''],items.map(t=>`<tr><td><strong>${esc(t.title)}</strong><small>${esc(data.plans.find(p=>p.id===t.plan_id)?.name)}</small></td><td>${esc(dep(t.department_id)?.name)}</td><td>${tag(t.priority)}</td><td>${t.shift_id?'Guardia #'+t.shift_id:'Sin vincular'}</td><td>${user.role==='chief'&&['draft','rejected'].includes(data.plans.find(p=>p.id===t.plan_id)?.status)?btn('Editar','edit-task','edit','small',`data-id="${t.id}"`)+btn('Retirar','delete-task','','small danger',`data-id="${t.id}"`):btn('Ver plan','open-plan','right','small',`data-id="${t.plan_id}"`)}</td></tr>`).join('')):empty('No hay tareas para mostrar','Registra las prioridades al preparar una planificación.')}</section>`;}
function usersPage(){return heading('Usuarios y roles','Administra las cuentas y sus responsabilidades.',btn('Crear usuario','new-user','plus','primary'))+`<section class="panel">${table(['Usuario','Correo','Rol','Estado',''],data.users.map(u=>`<tr><td><strong>${esc(u.name)}</strong></td><td>${esc(u.email)}</td><td>${roleNames[u.role]}</td><td>${tag(u.active?'Activo':'Inactivo')}</td><td>${btn('Editar','edit-user','edit','small',`data-id="${u.id}"`)}</td></tr>`).join(''))}</section>`;}
function reportsPage(){const items=report?.items||[];return heading('Reportes hospitalarios','Consulta la cobertura y los estados de autorización por período.',report?btn('Exportar CSV','export-csv','download')+btn('Imprimir / PDF','print','download','primary'):'')+`<form id="report-form" class="toolbar">${input('Desde','start',report?.start||today(),'date','required')}${input('Hasta','end',report?.end||addDays(today(),30),'date','required')}<button type="submit" class="btn primary">Aplicar período</button></form>${report?`<p class="print-only">Hospital RIP · Reporte del ${esc(report.start)} al ${esc(report.end)} · Emitido por ${esc(user.name)}</p><div class="stats">${stat('Guardias del período',items.length,'Según fecha de inicio','calendar')}${stat('Guardias cubiertas',items.filter(s=>s.doctor).length,'Con médico asignado','users')}${stat('Autorizadas',items.filter(s=>s.status==='approved').length,'Válidas para ejecución','shield')}${stat('Departamentos',new Set(items.map(s=>s.department)).size,'Con guardias en el período','building')}</div><section class="panel">${items.length?table(['Inicio','Guardia','Departamento','Médico','Estado'],items.map(s=>`<tr><td>${esc(s.starts_at)}</td><td><strong>${esc(s.label)}</strong><small>${esc(s.plan)}</small></td><td>${esc(s.department)}</td><td>${esc(s.doctor||'Sin asignar')}</td><td>${tag(s.status)}</td></tr>`).join('')):empty('Sin guardias en este período','Selecciona otro rango de fechas.')}</section><section class="panel report-summary"><h2>Directorio actual</h2><p>${data.doctors.filter(d=>d.active).length} médicos activos en ${data.departments.length} departamentos. Estos totales describen el directorio actual, sin filtro de fechas.</p>${btn('Exportar médicos','export-doctors','download','small')}${btn('Exportar departamentos','export-departments','download','small')}</section>`:empty('Selecciona un período','Aplica las fechas para consultar el reporte y habilitar las exportaciones.')}`;}
function auditPage(){return heading('Actividad del sistema','Registro de las últimas 250 acciones realizadas por el equipo.',btn('Actualizar','refresh','refresh'))+`<section class="panel">${table(['Fecha y hora','Usuario','Acción','Registro'],data.audit.map(a=>`<tr><td>${esc(a.created_at)}</td><td>${esc(a.user_name||'Sistema')}</td><td>${esc(a.action)}</td><td>${esc(a.entity)} #${a.entity_id||''}</td></tr>`).join(''))}</section>`;}
function bindPage(){if($('#search'))$('#search').oninput=e=>{const pos=e.target.selectionStart;search=e.target.value;$('#content').innerHTML=content();bindPage();$('#search').focus();$('#search').setSelectionRange(pos,pos);};if($('#department-filter'))$('#department-filter').onchange=e=>{departmentFilter=e.target.value;render();};if($('#report-form'))$('#report-form').onsubmit=async e=>{e.preventDefault();const b=Object.fromEntries(new FormData(e.currentTarget));try{report=await api(`reports?start=${b.start}&end=${b.end}`);render();}catch(err){toast(err.message);}};}
function modal(title,html,onSubmit,submitLabel='Guardar cambios'){$('#modal').innerHTML=`<div class="modal-heading"><h2>${title}</h2><button class="icon-btn" data-action="close-modal" aria-label="Cerrar">${icon('close')}</button></div><form id="modal-form">${html}<p class="form-error" role="alert"></p><div class="modal-actions">${btn('Cancelar','close-modal')}<button type="submit" class="btn primary">${submitLabel}</button></div></form>`;$('#modal').showModal();$('#modal-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,submit=$('[type=submit]',f);submit.disabled=true;try{const values=Object.fromEntries(new FormData(f));for(const cb of f.querySelectorAll('[type=checkbox]'))values[cb.name]=cb.checked;await onSubmit(values);$('#modal').close();if(user)await refresh();toast('Cambios guardados correctamente.');}catch(err){$('.form-error',f).textContent=err.message;}finally{submit.disabled=false;}};}
function doctorForm(d={}){modal(d.id?'Editar médico':'Registrar médico',input('Nombre completo','name',d.name,'text','required maxlength="100"')+`<div class="form-grid">${input('Identificación','identification',d.identification,'text','required maxlength="30"')}${input('Especialidad','specialty',d.specialty,'text','required maxlength="100"')}</div>`+select('Departamento','department_id',departmentOptions(),d.department_id)+input('Correo de contacto (opcional)','email',d.email,'email')+(d.id?`<label class="check"><input type="checkbox" name="active" ${d.active?'checked':''}>Médico activo</label>`:''),b=>api('doctors',{...b,id:d.id}));}
function departmentForm(d={}){modal(d.id?'Editar departamento':'Nuevo departamento',input('Nombre','name',d.name,'text','required maxlength="100"')+`<label>Descripción<textarea name="description" maxlength="400">${esc(d.description)}</textarea></label>`+input('Color en la agenda','color',d.color||'#537fa6','color')+(d.id?`<label class="check"><input type="checkbox" name="active" ${d.active?'checked':''}>Departamento activo</label>`:''),b=>api('departments',{...b,id:d.id}));}
function availabilityForm(a={}){modal(a.id?'Editar disponibilidad':'Registrar disponibilidad',select('Médico','doctor_id',data.doctors.filter(d=>d.active).map(d=>[d.id,d.name]),a.doctor_id)+`<div class="form-grid">${input('Desde','starts_at',a.starts_at?.replace(' ','T').slice(0,16)||today()+'T07:00','datetime-local','required')}${input('Hasta','ends_at',a.ends_at?.replace(' ','T').slice(0,16)||today()+'T19:00','datetime-local','required')}</div>`,b=>api('availability',{...b,id:a.id}));}
function planForm(p={}){modal(p.id?'Editar planificación':'Nueva planificación',input('Nombre de la planificación','name',p.name,'text','required maxlength="120" placeholder="Guardias · Semana del 21 de septiembre"')+`<div class="form-grid">${input('Fecha inicial','start_date',p.start_date||today(),'date','required')}${input('Fecha final','end_date',p.end_date||addDays(today(),6),'date','required')}</div><p class="form-help">Después podrás registrar guardias y tareas prioritarias. La propuesta se guarda como borrador.</p>`,async b=>{const result=await api('plans',{...b,id:p.id});selectedPlan=result.id;view='plans';});}
function shiftForm(s={},planId){const p=data.plans.find(p=>p.id===+(s.plan_id||planId));if(!p)return toast('Primero crea una planificación.');modal(s.id?'Editar guardia':'Agregar guardia',input('Nombre del turno','label',s.label||'Guardia de mañana','text','required maxlength="100"')+select('Departamento','department_id',departmentOptions(),s.department_id)+`<div class="form-grid">${input('Inicio','starts_at',s.starts_at?.replace(' ','T').slice(0,16)||p.start_date+'T07:00','datetime-local','required')}${input('Fin','ends_at',s.ends_at?.replace(' ','T').slice(0,16)||p.start_date+'T15:00','datetime-local','required')}</div>`+select('Médico disponible','doctor_id',[],s.doctor_id,true)+`<p class="form-help" id="doctor-hint">Solo aparecen médicos del departamento con disponibilidad para todo el turno y sin cruces.</p>`,b=>api('shifts',{...b,id:s.id,plan_id:p.id}));const f=$('#modal-form');const update=()=>{const values=Object.fromEntries(new FormData(f)),a=values.starts_at.replace('T',' ')+':00',b=values.ends_at.replace('T',' ')+':00';const options=data.doctors.filter(d=>d.active&&d.department_id===+values.department_id&&data.availability.some(v=>v.doctor_id===d.id&&v.starts_at<=a&&v.ends_at>=b)&&!data.shifts.some(v=>v.id!==s.id&&v.doctor_id===d.id&&v.starts_at<b&&v.ends_at>a));const prev=f.elements.doctor_id.value||s.doctor_id;f.elements.doctor_id.innerHTML='<option value="">Sin asignar · pendiente de cobertura</option>'+options.map(d=>`<option value="${d.id}" ${d.id===+prev?'selected':''}>${esc(d.name)}</option>`).join('');$('#doctor-hint').textContent=`${options.length} médicos compatibles. La disponibilidad también se valida al guardar.`;};['department_id','starts_at','ends_at'].forEach(k=>f.elements[k].onchange=update);update();}
function taskForm(t={},planId){const plans=data.plans.filter(p=>['draft','rejected'].includes(p.status));if(!plans.length)return toast('Crea una planificación en borrador para agregar tareas.');modal(t.id?'Editar tarea':'Nueva tarea',input('Descripción de la tarea','title',t.title,'text','required maxlength="180"')+select('Planificación','plan_id',plans.map(p=>[p.id,p.name]),t.plan_id||planId)+select('Departamento','department_id',departmentOptions(),t.department_id)+select('Prioridad','priority',[['high','Alta prioridad'],['normal','Normal']],t.priority||'high')+select('Guardia de cobertura','shift_id',[],t.shift_id,true)+`<p class="form-help">Las tareas de alta prioridad deben vincularse a una guardia con médico antes de enviar a revisión.</p>`,b=>api('tasks',{...b,id:t.id}));const f=$('#modal-form');if(t.id)f.elements.plan_id.disabled=true;const update=()=>{const plan=+(t.plan_id||f.elements.plan_id.value),department=+f.elements.department_id.value;f.elements.shift_id.innerHTML='<option value="">Sin vincular</option>'+data.shifts.filter(s=>s.plan_id===plan&&s.department_id===department).map(s=>`<option value="${s.id}" ${s.id===t.shift_id?'selected':''}>${fmt(s.starts_at)} ${s.starts_at.slice(11,16)} · ${esc(doc(s.doctor_id)?.name||'Sin médico')}</option>`).join('');};f.elements.plan_id.onchange=update;f.elements.department_id.onchange=update;update();if(t.id){const submit=f.onsubmit;f.onsubmit=e=>{f.elements.plan_id.disabled=false;return submit(e);};}}
function userForm(u={}){modal(u.id?'Editar usuario':'Crear usuario',input('Nombre completo','name',u.name,'text','required maxlength="100"')+input('Correo electrónico','email',u.email,'email','required')+select('Rol','role',Object.entries(roleNames),u.role||'chief')+input(u.id?'Nueva contraseña (dejar vacía para conservar)':'Contraseña inicial','password','','password',`${u.id?'':'required'} minlength="10" maxlength="128" autocomplete="new-password"`)+(u.id?`<label class="check"><input name="active" type="checkbox" ${u.active?'checked':''}>Cuenta activa</label>`:'')+`<p class="form-help">Cambiar una cuenta cerrará todas sus sesiones abiertas.</p>`,b=>api('users',{...b,id:u.id}));}
function confirmAction(title,description,endpoint,body,label='Confirmar'){modal(title,`<p class="muted">${description}</p>`,()=>api(endpoint,body),label);}
function csv(filename,headers,items){const cell=v=>{let s=String(v??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};const blob=new Blob(['\uFEFF'+[headers,...items].map(r=>r.map(cell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.addEventListener('click',async e=>{const el=e.target.closest('[data-action]');if(!el)return;const a=el.dataset.action,id=+el.dataset.id;try{
 if(a==='new-worker'||a==='edit-worker')workerForm(data.workers.find(w=>w.id===id));
 else if(a==='new-work-hours')workHoursForm();
 else if(a==='new-payroll')payrollForm();
 else if(a==='delete-work-hours')confirmAction('Retirar jornada','Se retirará esta jornada pendiente de liquidación.','work-hours/delete',{id},'Retirar');
 else if(a==='pay-payroll')modal('Registrar pago realizado','<p class="muted">Registra la referencia de la transferencia o del comprobante. Esta acción conserva el pago en el historial.</p>'+input('Referencia del pago','reference','','text','required minlength="3" maxlength="100"'),b=>api('payrolls/pay',{id,...b}),'Marcar como pagado');
 else if(a==='export-payroll')csv('Hospital_RIP_nomina.csv',['Trabajador','Identificación','Desde','Hasta','Horas','Salario COP','Estado','Referencia'],data.payrolls.map(p=>[p.worker_name,p.identification,p.start_date,p.end_date,p.minutes/60,p.total_cents/100,p.status==='paid'?'Pagado':'Pendiente',p.reference]));
 else if(a==='toggle-password'){const input=$('[name=password]');input.type=input.type==='password'?'text':'password';el.setAttribute('aria-label',input.type==='password'?'Mostrar contraseña':'Ocultar contraseña');}
 else if(a==='menu')$('.sidebar').classList.toggle('open');
 else if(a==='theme'){document.body.dataset.theme=document.body.dataset.theme==='dark'?'light':'dark';try{localStorage.setItem('rip-theme',document.body.dataset.theme);}catch{}}
 else if(a==='logout'){await api('logout',{});user=null;data={};selectedPlan=null;report=null;login();}
 else if(a==='refresh')await refresh();
 else if(a==='close-modal')$('#modal').close();
 else if(a==='account')modal('Mi cuenta',`<p class="muted">${esc(user.name)} · ${roleNames[user.role]}<br>${esc(user.email)}</p>`+input('Contraseña actual','current','','password','required autocomplete="current-password"')+input('Nueva contraseña','password','','password','required minlength="10" maxlength="128" autocomplete="new-password"')+`<p class="form-help">Al cambiar tu contraseña tendrás que iniciar sesión de nuevo.</p>`,async b=>{await api('password',b);user=null;login();},'Cambiar contraseña');
 else if(a==='today'||a==='previous-week'||a==='next-week'){week=a==='today'?today():addDays(week,a==='previous-week'?-7:7);render();}
 else if(a==='go-plans'){view='plans';selectedPlan=null;render();}
 else if(a==='open-plan'){selectedPlan=id;view='plans';render();}
 else if(a==='back-plans'){selectedPlan=null;render();}
 else if(a==='new-doctor'||a==='edit-doctor')doctorForm(data.doctors.find(d=>d.id===id));
 else if(a==='new-department'||a==='edit-department')departmentForm(data.departments.find(d=>d.id===id));
 else if(a==='new-plan'||a==='edit-plan')planForm(data.plans.find(p=>p.id===id));
 else if(a==='new-shift'||a==='edit-shift')shiftForm(data.shifts.find(s=>s.id===id),el.dataset.plan);
 else if(a==='new-task'||a==='edit-task')taskForm(data.tasks.find(t=>t.id===id),el.dataset.plan);
 else if(a==='new-user'||a==='edit-user')userForm(data.users.find(u=>u.id===id));
 else if(a==='new-availability'||a==='edit-availability')availabilityForm(data.availability.find(v=>v.id===id));
 else if(a==='deactivate-department'||a==='activate-department'){const d=data.departments.find(d=>d.id===id),active=a==='activate-department';confirmAction(active?'Reactivar departamento':'Desactivar departamento',active?'El departamento volverá a estar disponible para nuevos registros.':'No se eliminará el historial. Debes retirar médicos activos y guardias futuras antes de desactivarlo.','departments',{...d,active},active?'Reactivar':'Desactivar');}
 else if(a==='delete-availability')confirmAction('Retirar disponibilidad','Se retirará este intervalo. La operación se bloqueará si tiene guardias asignadas.','availability/delete',{id},'Retirar');
 else if(a==='delete-shift')confirmAction('Retirar guardia','La guardia se eliminará del borrador. Las tareas vinculadas quedarán pendientes de cobertura.','shifts/delete',{id},'Retirar');
 else if(a==='delete-task')confirmAction('Retirar tarea','Se eliminará esta tarea de la planificación.','tasks/delete',{id},'Retirar');
 else if(a==='delete-plan')confirmAction('Eliminar planificación','Se eliminarán esta planificación, sus guardias y tareas. Solo se permiten borradores o propuestas rechazadas.','plans/delete',{id},'Eliminar');
 else if(a==='submit-plan')confirmAction('Enviar a revisión','Se comprobarán todas las guardias y tareas prioritarias. La planificación quedará bloqueada durante la revisión del supervisor.','plans/submit',{id},'Enviar a revisión');
 else if(a==='approve-plan'||a==='reject-plan'){const p=data.plans.find(p=>p.id===id),reject=a==='reject-plan';modal(reject?'Rechazar planificación':'Autorizar planificación',`<p class="muted">${esc(p.name)}</p><label>Observaciones ${reject?'(obligatorias)':'(opcionales)'}<textarea name="note" maxlength="1000" ${reject?'required minlength="5"':''}></textarea></label>`,b=>api('plans/review',{id,version:p.version,status:reject?'rejected':'approved',note:b.note}),reject?'Confirmar rechazo':'Autorizar');}
 else if(a==='print')window.print();
 else if(a==='export-csv')csv('Hospital_RIP_guardias.csv',['Inicio','Fin','Guardia','Departamento','Médico','Planificación','Estado'],report.items.map(s=>[s.starts_at,s.ends_at,s.label,s.department,s.doctor||'Sin asignar',s.plan,states[s.status]]));
 else if(a==='export-doctors')csv('Hospital_RIP_medicos.csv',['Identificación','Nombre','Especialidad','Departamento','Activo'],data.doctors.map(d=>[d.identification,d.name,d.specialty,dep(d.department_id)?.name,d.active?'Sí':'No']));
 else if(a==='export-departments')csv('Hospital_RIP_departamentos.csv',['Departamento','Descripción','Médicos activos'],data.departments.map(d=>[d.name,d.description,data.doctors.filter(m=>m.department_id===d.id&&m.active).length]));
 }catch(err){toast(err.message);}});
window.addEventListener('hashchange',()=>{view=location.hash.slice(1)||'home';selectedPlan=null;search='';departmentFilter='';if(user)render();});
window.addEventListener('offline',()=>toast('Sin conexión. Recupera la red para consultar o guardar cambios.'));
try{user=(await api('me')).user;view=location.hash.slice(1)||'home';await refresh();}catch{login();}
